# -*- coding: utf-8 -*-
"""ITC-Financial-Analysis-Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sKNdGSmvcTmLsdMMYkq2v03q1FZbG_Q

# Scraping ITC website using Tavily AI
"""

! pip install tavily-python

from langchain.docstore.document import Document

from google.colab import userdata
key = userdata.get('tavily_ai_key')

"""## 1. Extracting ITC Annual Reports for the years - 2023, 2024."""

# To install: pip install tavily-python
# from tavily import TavilyClient
# client = TavilyClient(key)
# response = client.extract(
#     urls=["https://www.itcportal.com/about-itc/shareholder-value/annual-reports/itc-annual-report-2024/pdf/ITC-Report-and-Accounts-2024.pdf","https://www.itcportal.com/about-itc/shareholder-value/annual-reports/itc-annual-report-2023/pdf/ITC-Report-and-Accounts-2023.pdf"],
#     extract_depth="advanced"
# )
# print(response)

# response['results'][0]['raw_content']

# doc1 = Document(
#         page_content = response['results'][0]['raw_content'],
#         metadata={"Source": "ITC Annual Report For the Year 2024"}
#     )

# doc2 = Document(
#         page_content = response['results'][1]['raw_content'],
#         metadata={"Source": "ITC Annual Report For the Year 2023"}
#     )



"""## 2. With Similar Logic Scraping all the data:
 - 2023-24 -> Annual Reports
 - 2023-25 -> Standalone Quarterly Reports and Consolidated Quarterly Reports
 - 2023-25 -> Investor Presentations
"""

from tavily import TavilyClient
from langchain.schema import Document

client = TavilyClient(key)

pdf_sources = [
    # Annual Reports of 2023-2024
    {
        "url": "https://www.itcportal.com/about-itc/shareholder-value/annual-reports/itc-annual-report-2023/pdf/ITC-Report-and-Accounts-2023.pdf",
        "metadata": {"source": "ITC Report and Accounts 2023"}
    },
    {
        "url": "https://www.itcportal.com/about-itc/shareholder-value/annual-reports/itc-annual-report-2024/pdf/ITC-Report-and-Accounts-2024.pdf",
        "metadata": {"source": "ITC Report and Accounts 2024"}
    },
    # Presentation 2023
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q1-FY2023.pdf",
        "metadata": {"source": "Quarterly Financial Statement Q1 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q2-FY2023.pdf",
        "metadata": {"source": "Quarterly Financial Statement Q2 FY2023"}
    },
    # {
    #     "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q3-FY2023.pdf",
    #     "metadata": {"source": "Quarterly Financial Statement Q3 FY2023"}
    # },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q4-FY2023.pdf",
        "metadata": {"source": "Quarterly Financial Statement Q4 FY2023"}
    },
    # Presentation 2024
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q1-FY2024.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q1 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q2-FY2024.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q2 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q3-FY2024.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q3 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q4-FY2024.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q4 FY2024"}
    },
    # Presentation 2025
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q1-FY2025.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q1 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q2-FY2025.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q2 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q3-FY2025.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q3 FY2025"}
    },
    # Standalone Financial Report 2023
    # {
    #     "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2023-sfs.pdf",
    #     "metadata": {"source": "Standalone Financial Result Q1 FY2023"}

    # },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2023-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q2 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2023-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q3 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q4-FY2023-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q4 FY2023"}
    },
    # Standalone Financial Report 2024
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2024-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q1 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2024-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q2 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2024-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q3 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q4-FY2024-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q4 FY2024"}
    },
    # Standalone Financial Report 2025
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2025-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q1 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2025-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q2 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2025-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q3 FY2025"}
    },
    # Consolidated Financial Report 2023
    # {
    #     "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2023-cfs.pdf",
    #     "metadata": {"source": "Consolidated Financial Result Q1 FY2023"}
    # },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2023-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q2 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2023-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q3 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q4-FY2023-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q4 FY2023"}
    },
    # Consolidated Financial Report 2024
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2024-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q1 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2024-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q2 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2024-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q3 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q4-FY2024-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q4 FY2024"}
    },
    # Consolidated Financial Report 2025
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2025-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q1 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2025-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q2 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2025-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q3 FY2025"}
    }
]

# pdf_sources

# Loop through all PDFs, extract content, and create Document objects
documents = []
for pdf in pdf_sources:
    response = client.extract(urls=[pdf["url"]], extract_depth="advanced")
    content = response["results"][0]["raw_content"]
    documents.append(Document(page_content=content, metadata=pdf["metadata"]))

# Optional: Print one sample
print(documents[0])

# documents[-1].keys()

"""## 3. Preprocessing"""

import re

def cleaning(text):

    # Lower
    text = text.lower()

    # Remove HTML tags
    text = re.sub(r'<[^>]+>', ' ', text)

    # Remove URLs (http, https, www)
    text = re.sub(r'http\S+|www\.\S+', ' ', text)

    # Remove Markdown links: [text](link)
    text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)

    # Remove HTML links: <a href="...">text</a> (already removed by HTML tag regex, but just in case)
    text = re.sub(r'<a\s+(?:[^>]?\s+)?href="[^"]">(.*?)</a>', r'\1', text)

    return text

# Applying Cleaning function on document text
for doc in documents:
  doc.page_content = cleaning(doc.page_content)

documents[0].page_content

"""## 4. Saving the Documents"""

import pickle
from langchain.schema import Document

# Example: docs is your list of Document objects
docs_to_save = documents  # assuming `documents` is your list of Document objects

with open("documents_Final.pkl", "wb") as f:
    pickle.dump(docs_to_save, f)

